//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce_Olx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Order
    {
        public int order_id { get; set; }
        public Nullable<int> order_product_fk { get; set; }
        public Nullable<int> order_user_fk { get; set; }
        public Nullable<int> order_invoice_fk { get; set; }
        public Nullable<double> order_bill { get; set; }
        public Nullable<double> order_unit_price { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public int order_quantity { get; set; }
    
        public virtual Table_Invoice Table_Invoice { get; set; }
        public virtual Table_Product Table_Product { get; set; }
        public virtual Table_User Table_User { get; set; }
    }
}
