//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce_Olx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Invoice()
        {
            this.Table_Order = new HashSet<Table_Order>();
        }
    
        public int invoice_id { get; set; }
        public Nullable<System.DateTime> inovice_date { get; set; }
        public Nullable<int> invoice_userr_ID_foreign_key { get; set; }
        public Nullable<int> invoice_bill { get; set; }
    
        public virtual Table_User Table_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Order> Table_Order { get; set; }
    }
}
