//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce_Olx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Product()
        {
            this.Table_Order = new HashSet<Table_Order>();
        }
    
        public int product_ID { get; set; }
        public string product_NAME { get; set; }
        public string product_IMAGE { get; set; }
        public string product_PRICE { get; set; }
        public string product_DESCRIPTION { get; set; }
        public Nullable<int> category_ID_foreign_key { get; set; }
        public Nullable<int> userr_ID_foreign_key { get; set; }
    
        public virtual Table_Category Table_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Order> Table_Order { get; set; }
        public virtual Table_User Table_User { get; set; }
    }
}
