//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce_Olx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Admin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Admin()
        {
            this.Table_Category = new HashSet<Table_Category>();
        }
    
        public int admin_ID { get; set; }
        public string admin_NAME { get; set; }
        public string admin_EMAIL { get; set; }
        public string admin_PASSWORD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Category> Table_Category { get; set; }
    }
}
