//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce_Olx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_User()
        {
            this.Table_Invoice = new HashSet<Table_Invoice>();
            this.Table_Order = new HashSet<Table_Order>();
            this.Table_Product = new HashSet<Table_Product>();
        }
    
        public int userr_ID { get; set; }
        public string userr_NAME { get; set; }
        public string userr_EMAIL { get; set; }
        public string userr_CONTACT { get; set; }
        public string userr_IMAGE { get; set; }
        public string userr_PASSWORD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Invoice> Table_Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Order> Table_Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Product> Table_Product { get; set; }
    }
}
